# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: tests
    silent: true
  run:
    cmds:
      - odin run digitd
    silent: true
  debug:
    deps:
      - build_debug
    cmds:
      - lldb ./digitd.bin
    silent: true
    aliases:
      - d
  build:
    cmds:
      - odin build digitd
    aliases: [b]
  build_debug:
    cmds:
      - odin build digitd -debug -o:none
    aliases: [bd]
  tests:
    deps: [digitd_tests]
    aliases: [t]
  digitd_tests:
    cmds:
      - odin run digitd_tests
    silent: true
    sources:
      - ./digitd/*
      - ./digitd_tests/*
    aliases: [dt]
  clean:
    cmds:
      - rm ./*.bin
    silent: true

interval: 250ms
