# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: tests
    silent: true
  run:
    deps:
      - build
    cmds:
      - ./digitd.bin 1079
    silent: true
  debug:
    deps:
      - build_debug
    cmds:
      - lldb ./digitd.bin 1079
    silent: true
    aliases:
      - d
  build:
    cmds:
      - odin build digitd
    aliases:
      - b
    silent: true
  build_debug:
    cmds:
      - odin build digitd -debug -o:none
    aliases: 
      - bd
  tests:
    deps:
      - digitd_tests
    aliases: 
      - t
  digitd_tests:
    cmds:
      - odin run digitd_tests
    silent: true
    sources:
      - ./digitd/*
      - ./digitd_tests/*
    aliases: 
      - dt
  clean:
    cmds:
      - rm ./*.bin
    silent: true

interval: 250ms
